import { Analytics } from '@vercel/analytics/next'
import { Inter } from 'next/font/google'
import './globals.css'
// import type { Metadata } from 'next'

const inter = Inter({
  variable: '--font-inter',
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900']
})

// export const metadata: Metadata = {
//   title: 'Andre Victoria',
//   description: 'Generated by create next app',
//   keywords: ['Next.js', 'React', 'Web App', 'Inter Font'],
//   authors: [{ name: 'Andre Victorias', url: 'https://dre-dev.vercel.app/' }],
//   openGraph: {
//     title: 'Andre Victoria',
//     description: 'Andre Victoria Portfolio',
//     url: 'https://dre-dev.vercel.app/',
//     siteName: 'Andre Victoria',
//     images: [
//       {
//         url: 'https://dre-dev.vercel.app/image.png',
//         width: 1200,
//         height: 630,
//         alt: 'Dre-dev'
//       }
//     ],
//     locale: 'en_US',
//     type: 'website'
//   },
//   icons: {
//     icon: '/favicon.ico',
//     shortcut: '/favicon.ico'
//   }
// }

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <body className={`${inter.variable} antialiased`}>
        {children}
        <Analytics />
      </body>
    </html>
  )
}
